from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from backend.app.domain.models import (
    ActionRecord,
    DashboardMetrics,
    MessageDelivery,
    PubSubMessage,
    Ticket,
    TicketEvent,
    WorkflowJob,
    WorkflowState,
    WorkOrder,
)


class OperationsRepository(Protocol):
    """Persistence port. DynamoDB can implement this contract without domain changes."""

    def initialize(self) -> None: ...
    def reset(self) -> None: ...
    def create_ticket(self, ticket: Ticket) -> Ticket: ...
    def create_ticket_and_job(self, ticket: Ticket, job: WorkflowJob) -> Ticket: ...
    def save_ticket(self, ticket: Ticket) -> Ticket: ...
    def save_ticket_and_job(self, ticket: Ticket, job: WorkflowJob) -> Ticket: ...
    def get_ticket(self, ticket_id: str) -> Ticket | None: ...
    def list_tickets(self) -> list[Ticket]: ...
    def append_event(self, event: TicketEvent) -> bool: ...
    def list_events(self, ticket_id: str) -> list[TicketEvent]: ...
    def enqueue_job(self, job: WorkflowJob) -> bool: ...
    def claim_due_jobs(self, now: datetime, limit: int = 10) -> list[WorkflowJob]: ...
    def complete_job(self, job_id: str) -> None: ...
    def retry_job(self, job_id: str, error: str, available_at: datetime) -> None: ...
    def list_jobs(self, ticket_id: str | None = None) -> list[WorkflowJob]: ...
    def publish_message(self, message: PubSubMessage, subscriptions: list[str]) -> bool: ...
    def claim_deliveries(
        self, subscription: str, now: datetime, limit: int = 1, lease_seconds: float = 30
    ) -> list[MessageDelivery]: ...
    def complete_delivery(self, subscription: str, message_id: str) -> None: ...
    def retry_delivery(
        self,
        subscription: str,
        message_id: str,
        error: str,
        available_at: datetime,
        *,
        dead_letter: bool = False,
    ) -> None: ...
    def message_stats(self) -> dict[str, int]: ...
    def workflow_deliveries(self) -> list[dict[str, Any]]: ...
    def save_workflow_state(self, state: WorkflowState) -> WorkflowState: ...
    def get_workflow_state(self, ticket_id: str) -> WorkflowState | None: ...
    def save_action(self, action: ActionRecord) -> ActionRecord: ...
    def get_action(self, action_id: str) -> ActionRecord | None: ...
    def list_actions(self, ticket_id: str) -> list[ActionRecord]: ...
    def save_work_order(self, work_order: WorkOrder) -> WorkOrder: ...
    def get_work_order_for_ticket(self, ticket_id: str) -> WorkOrder | None: ...
    def get_state(self, key: str) -> dict[str, Any] | None: ...
    def set_state(self, key: str, value: dict[str, Any]) -> None: ...
    def metrics(self) -> DashboardMetrics: ...
